In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(20,10)

array([], dtype=int32)

In [18]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [20]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

maximum 3 arguments can be taken

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

this is called hyper parameter 

In [24]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [33]:
rand(3,2)

NameError: name 'rand' is not defined

In [34]:
random.rand(3,2)

NameError: name 'random' is not defined

In [38]:
np.random.rand(34)

array([0.81715901, 0.81078095, 0.388988  , 0.34866006, 0.40838351,
       0.46756311, 0.1862609 , 0.21250753, 0.20933313, 0.97933508,
       0.97358085, 0.51661809, 0.47786926, 0.82172467, 0.62114785,
       0.57874769, 0.86345019, 0.3672579 , 0.44570511, 0.56935455,
       0.91215709, 0.1385902 , 0.29895918, 0.61484511, 0.58630251,
       0.78074116, 0.89046601, 0.37057924, 0.57952786, 0.04946991,
       0.89674112, 0.08502141, 0.83789078, 0.14428969])

In [39]:
np.random.rand(3,5)

array([[0.97511079, 0.03052698, 0.87415709, 0.78487066, 0.25043052],
       [0.47742877, 0.00737818, 0.94060196, 0.7062409 , 0.69262945],
       [0.08210454, 0.35071173, 0.96146583, 0.13588594, 0.22847898]])

In [49]:
np.random.randint(4,6)

4

In [52]:
np.random.randint(2,20,4)

array([17,  3, 11, 16])

In [53]:
np.random.randint(0,1)

0